services:
  - type: web
    name: naruto
    env: node
    buildCommand: yarn install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production